name: run example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: install graphviz
        run: sudo apt install graphviz
      - name: run example
        run: |
          cd examples/
          go run main.go
          ls -l
      - name: check generated files
        run: |
          if [ -f examples.png ]; then
            echo "File exists"
          else
            echo "File not found"
            exit 1
          fi
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[AUTO]"
          branch: master
          commit_options: '--no-verify --signoff'
          repository: .
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: true
          disable_globbing: true
